[package]
name = "hashing"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
blake3.workspace = true
md-5.workspace = true
sha1.workspace = true
hex.workspace = true
chrono.workspace = true
uuid.workspace = true
tokio = { workspace = true, features = ["io-util"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
