[package]
name = "timeline"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
csv.workspace = true
chrono.workspace = true
uuid.workspace = true
tracing.workspace = true
metadata = { path = "../metadata" }

[dev-dependencies]
tempfile.workspace = true
